name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Build for Linux
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/letgofur-linux-amd64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/letgofur-linux-amd64
          draft: false
          prerelease: false
          generate_release_notes: true
